# Generated by Django 2.0.2 on 2018-04-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential', models.CharField(max_length=10)),
                ('pipeline', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('account_risk', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplarrapp.AccountChild'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplarrapp.AccountRisk'),
        ),
    ]
